# Generated by Django 3.1.2 on 2020-10-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='confirm_password',
            field=models.CharField(default='aa', max_length=120),
        ),
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default='aa', max_length=120),
        ),
    ]
